### ISSUE TITLE
Rate Limit hit when running experimental feature - Export App Sign On Policies

### ISSUE THREAD

**Issue by itbharsh** [oktadeveloper/rockstar#10] opened 2023-02-02 16:37 UTC
We are hitting a rate limit for "/admin*" and thus only getting only partial records exported from the "Export App Sign On Policies (experimental)" feature found in the Rockstar plugin when looking at "Applications".  We understand that this is "experimental" but wanted to report the issue nevertheless so you are aware.

In addition to the issue above, I have a question for you about "Export Apps".  It seems that in one of our tenants where Okta shows we have 495 active and 6 inactive apps when I use the Rockstar "Export Apps" feature it says 538 apps exported.  Because there are so many apps and no easy way to pull a list from Okta's admin other than Rockstar I cannot tell why these counts don't add up.  Do you have any ideas on why the Okta Admin screen shows less apps than what Rockstar "Export Apps" returns?

Thank you for your time!  We continue to really like what you are doing with Rockstar and appreciate all the hard work you have put into it.  Keep it up!!!

**Comment by gabrielsroka** [comment] 2023-02-02 17:11
> experimental

I'll take a look, but that's what "experimental" means.

> apps

i've noticed Okta undercounts by usually 3 apps. i'm not sure why you're seeing so many. keep in mind that AD/LDAP/etc integrations are actually apps, but they don't show in the Apps screen. take a look at the CSV and see what the difference is. you can also ask Okta Support to export it from their admin screen if you like.

**Comment by gabrielsroka** [comment] 2023-02-02 17:17
eg, my org's app export CSV has 746 apps = 690 active + 45 inactive + 6 directory integrations + 3 Okta apps (the 3 i mentioned in my previous post) + ??

**Comment by gabrielsroka** [comment] 2023-02-02 17:22
you can also use rockstar's API Explorer on the private API:

```
/api/v1/internal/apps?limit=1000
```

or

```
/api/v1/internal/apps?filter=INACTIVE
```

or 

```
/api/v1/internal/apps?filter=ACTIVE
```

etc

![image](https://user-images.githubusercontent.com/14354736/216396269-05b2cec8-e63a-43de-8e49-f57241be971c.png)

**Comment by itbharsh** [comment] 2023-02-02 17:32
I did not consider "AD/LDAP/etc integrations are actually apps" so that accounts for 30 more.

I get (length: 509) when I run /api/v1/internal/apps?limit=1000

"i've noticed Okta undercounts by usually 3 apps"  I think I know what 2 of the 3 are.  We recently ran into 2 hidden apps showing for a custom policy that got created during our upgrade from Classic to OIE.  The two apps are "Okta Help Center" and "RSA SecurID".

**Comment by gabrielsroka** [comment] 2023-02-02 17:43
these 3 Okta apps:

![image](https://user-images.githubusercontent.com/14354736/216401190-d333ebf8-f3da-43c9-b57e-344770e4de6d.png)

**Comment by gabrielsroka** [comment] 2023-02-02 18:15
I just ran the Export App Sign On Policies and it worked fine. It goes to sleep a lot (which is expected). I opened the browser's DevTools (F12 on Windows) and looked at the Network tab to see what was happening.

If you want to setup a debugging session, email me at gabrielsroka.rockstar@gmail.com and I can take a look.

Note also: 
https://github.com/gabrielsroka/gabrielsroka.github.io/issues/14

and maybe also
https://github.com/gabrielsroka/gabrielsroka.github.io/issues/22 

By the way, this is the wrong repo. Please use https://github.com/gabrielsroka/gabrielsroka.github.io/issues

> Thank you for your time! We continue to really like what you are doing with Rockstar and appreciate all the hard work you have put into it. Keep it up!!!

Thanks for the kind words!

**Comment by itbharsh** [comment] 2023-02-02 18:16
For me the 3 apps (Okta Admin Console,Okta Browser Plugin, Okta Dashboard) all show up in the Okta Admin list of apps screen, the Rockstar Apps export dataset and in the list of apps when the internal API was called.

**Comment by gabrielsroka** [comment] 2023-02-02 18:19
yes, but did u notice the counts in my screenshot? it's from an OIE tenant, but i think the issue occurs in Okta Classic, too...

**Comment by itbharsh** [comment] 2023-02-02 18:22
Thanks for your feedback and sorry I posted in the wrong place.  I'm not sure a debugging session will do much for me as it seems we are just hitting a rate limit you are not.  Perhaps we have a lower rate limit on our tenant or more policies than you.  If you think a debugging session would be helpful for the betterment of the Rockstar plugin I would be willing to have one otherwise I'll just refrain from using that experimental export feature.  I understand that experimental things may have issues. I just wanted you to know that I found one in case that helped you in some way.

**Comment by gabrielsroka** [comment] 2023-02-02 18:25
It's up to you. I can't fix it if I can't repro in my tenants.

By the way, are you on OIE or Okta Classic? This export was designed for Classic, it scrapes the HTML since Classic doesn't have any APIs (that I know of). OIE, OTOH, does have APIs.

**Comment by itbharsh** [comment] 2023-02-02 19:01
We upgraded to OIE back in Dec.

**Comment by gabrielsroka** [comment] 2023-02-02 19:07
lol. i shoud have started with that. please check 
https://developer.okta.com/docs/reference/api/policy

**Comment by itbharsh** [comment] 2023-02-02 19:30
I used the "/api/v1/policies/{{policy id}}/app" API the other day since I didn't see a way to fetch all apps for all policies.  Am I missing something in this API you think I should be using?

If there is a way to tell an OIE tenant from Classic, maybe the Rockstar plugin can show, hide or change functionality based on which the tenant is running.  If there is not an easy way, maybe there could be a toggle button in the plugin that would allow the end user to choose classic or oie so that the plugin knows.  If there are not many features that are classic only or OIE only specific then maybe just adding a label like "classic only" or "OIE only" would be helpful.

Thanks for reviewing everything with me today and being open to suggestions on how this valuable tool can be improved.

**Comment by gabrielsroka** [comment] 2023-02-02 19:36
> fetch all apps for all policies

Please see the example code I've sent you above. 

> OIE

The status bar at the bottom of every page in the admin console will have a C for classic and an E for OIE. Rockstar could scrape that or at least let customers know to do that.

**Comment by gabrielsroka** [comment] 2023-02-02 19:39
this is for cloning policy rules, but the code might help u:

https://github.com/gabrielsroka/gabrielsroka.github.io/blob/master/CloneAppRules.html

**Comment by gabrielsroka** [comment] 2023-02-19 18:39
Were you able to get that to work? Can we close this?

**Comment by itbharsh** [comment] 2023-02-19 23:50
Since our tenant is OIE feel free to close.  Thanks for your time and keep up the good work!!!

**Comment by gabrielsroka** [comment] 2023-02-19 23:54
I don't have permission to close this issue. Would you please close it?

**Closed as completed** 2023-02-19 23:56 UTC
